### ISSUE TITLE
When editing value for 'time spent' or 'time remaining,' the new value becomes added to the total hours spent/remaining, rather than replacing it. 

### ISSUE THREAD

**Issue by Kaiser97** [Strafos/Issue-Manager#9]

**Comment by Strafos** [comment]
I've read this through a couple times and still don't understand what you're talking about.

I think it would be more clear in a format like this:
This is what I do:
1. I have an issue at 4 hours remaining
2. I edit the time remaining from 4 to 5

This is what I expect to happen:
Hours remaining becomes 5 for that issue

This is what actually happens:
Hours remaining becomes 20

**Comment by Strafos** [comment]
I am 90% sure that I figured out what was causing this and I've fixed it. The only reason I'm 90% sure is because I'm still unclear what your actual issue is
